name = "sidequest-subscription-lifecycle-cron"
main = "src/index.js"
compatibility_date = "2026-08-19"

[vars]
PTERODACTYL_PANEL_URL = "https://panel.sidequestservers.com"

[triggers]
crons = ["15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "sidequest-orders"
database_id = "0782cf5e-9672-4697-8497-1612652106eb"
